# this file defines "patches" for specific drupal.org advisories

[SA-CONTRIB-2024-025]
field_affected_versions = [
  '<1.0.13 || >=1.1.0 <1.1.0-beta3',
  '<1.0.13 || >=1.1.0-beta1 <1.1.0-beta3'
]
[SA-CORE-2022-002]
field_affected_versions = [
  '>7.0 <=7.86',
  '>=7.0 <=7.86'
]

[SA-CONTRIB-2022-047]
field_affected_versions = [
  '<1.0.6',
  '<1.6.0'
]

[SA-CONTRIB-2024-042]
field_affected_versions = [
  '<1.8.0 || >=2.0.0 <2.0.0-beta3',
  '<1.8.0 || >=2.0.0-beta1 <2.0.0-beta3'
]

[SA-CONTRIB-2019-019]
field_affected_versions = [
  '<1.25.0 || >=2.0.0 >2.3.0',
  '<1.25.0 || >=2.0.0 <2.3.0'
]

[SA-CONTRIB-2023-013]
field_affected_versions = [
  '<1.06',
  '<1.6'
]

[SA-CONTRIB-2024-004]
field_affected_versions = [
  '<12.05',
  '<12.0.5'
]

[SA-CONTRIB-2024-038]
field_affected_versions = [
  '<12.3.8 || >=12.4.0 <12.4.5 || >=13.0.0 <13.0.0-alpha11',
  '<12.3.8 || >=12.4.0 <12.4.5 || >=13.0.0-alpha1 <13.0.0-alpha11'
]

[SA-CONTRIB-2022-028]
field_affected_versions = [
  '<1.17.0 || =2.0.0',
  '<1.17.0 || 2.0.0'
]

[SA-CONTRIB-2023-031]
field_affected_versions = [
  '<1.2.2 || >=1.3.0 <1.3.0-rc3',
  '<1.2.2 || >=1.3.0-beta1 <1.3.0-rc3'
]

[SA-CONTRIB-2025-001]
field_affected_versions = [
  '>2.0.0 <2.0.3',
  '>=2.0.0 <2.0.3'
]

[SA-CONTRIB-2025-003]
field_affected_versions = [
  '>1.0.0 <1.0.2',
  '>=1.0.0 <1.0.2'
]

[SA-CONTRIB-2023-030]
field_affected_versions = [
  '^1 <= 1.0.0',
  '>=1.0.0 <1.1.0'
]
