[project]
name = "drupal-advisory-database"
requires-python = ">= 3.13"
dependencies = [
  "mypy (>=1.15.0,<2.0.0)",
  "requests (>=2.32.3,<3.0.0)",
  "ruff ~=0.11.5",
  "semver (>=3.0.4,<4.0.0)",
  "types-requests (>=2.32.0.20250328,<3.0.0.0)",
]

[tool.poetry]
package-mode = false

[tool.mypy]
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
strict_concatenate = true
check_untyped_defs = false
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_any_generics = false
disallow_untyped_calls = false
disallow_incomplete_defs = false
disallow_untyped_defs = false
no_implicit_reexport = true
warn_return_any = false
