indent-width = 2

[format]
quote-style = 'single'

[lint]
ignore = ['E501']
select = [
  'E',   # pycodestyle
  'F',   # Pyflakes
  'UP',  # pyupgrade
  'B',   # flake8-bugbear
#  'SIM', # flake8-simplify
#  'I'    # isort
]
