name: CI
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs of this workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  ruff:
    permissions:
      contents: read # to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: 'pyproject.toml'
          args: 'check'
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: 'pyproject.toml'
          args: 'format --check --diff'
  mypy:
    permissions:
      contents: read # to fetch (actions/checkout)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - run: pipx install poetry~=2.0
      - run: poetry install
      - run: poetry run mypy .
  prettier:
    permissions:
      contents: read # to fetch (actions/checkout)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
      - run: npx prettier --check .
